version: '3'
services:
  backend:
    image: node:latest
    restart: always
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "3000:3000"
    command: bash -c 'yarn && yarn start'